# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8add1867c7c1cd4c2635dbc2ae828731a6880cc8f1356203621b7d95a9cfaa6b0930eb69847f893ac70793b7a161cb152aed2387c5c879ea3c95e453e0e4bb7d

test:
  secret_key_base: ecaf97c7c1664fbba9d1739efb7b12da6ea9e0d2d5c32932cd6dbd39b1046aaa8f78614731a329d4ab87731ef290edd8e9cdf7479acd3f4b62d87b269e523d15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
